# Generated by Django 4.2.13 on 2024-06-14 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_feedback_email_alter_feedback_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
