# Generated by Django 4.2.13 on 2024-06-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0003_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('typeForName', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('gost', models.CharField(max_length=100)),
                ('base', models.CharField(max_length=500)),
                ('pack', models.CharField(max_length=200000)),
                ('area', models.CharField(max_length=200000)),
                ('feature', models.CharField(max_length=200000)),
                ('characteristic', models.CharField(max_length=200000)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='static/img/products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='static/img/products/')),
            ],
        ),
    ]
