# Generated by Django 4.2.13 on 2024-06-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristic',
            field=models.TextField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack',
            field=models.TextField(max_length=200000),
        ),
    ]
