# Generated by Django 4.2.13 on 2024-06-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gost',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='typeForName',
            field=models.CharField(max_length=100),
        ),
    ]
