# Generated by Django 4.2.13 on 2024-06-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_alter_product_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='area',
            field=models.TextField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='product',
            name='base',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.TextField(max_length=200000),
        ),
    ]
